### ISSUE TITLE
deprecated HTML

### ISSUE THREAD

**Issue by DiscoDancer** [aspnet/AspNetCore.Docs.ru-ru#47]
Hello.

I am using dotnet core 2.2 and vs2019. I have followed all steps, and in delete step you have and this.

```
@page "{id:int}"
@model ContosoUniversity.Pages.Students.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<p class="text-danger">@Model.ErrorMessage</p>

<h3>Are you sure you want to delete this?</h3>
<div>
```

and I have that:
```
@page "{id:int}"
@model ContosoUniversity.Pages.Students.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<p class="text-danger">@Model.ErrorMessage</p>

<h3>Are you sure you want to delete this?</h3>
<div>
```

`<h2>Delete</h2>` h size is the difference.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 8f592059-3328-88a8-5c6c-43121ac8a0a5
* Version Independent ID: f8a63abf-824b-5b80-e03d-abcb2c162b95
* Content: [Razor Pages с EF Core в ASP.NET Core — CRUD — 2 из 8](https://docs.microsoft.com/ru-ru/aspnet/core/data/ef-rp/crud?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/data/ef-rp/crud.md](https://github.com/aspnet/AspNetCore.Docs.ru-ru/blob/live/aspnetcore/data/ef-rp/crud.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Recommend close. The tutorial is not about headings `<h2>`

**Comment by DiscoDancer** [comment]
@Rick-Anderson Hello, first of all thanks for great docs, I have been enoying reading it. Maybe I can investigate this further? Like going to source of asp net scafolding and look for that header, and then come back with results and pull request.

**Comment by Rick-Anderson** [comment]
@DiscoDancer do a PR at https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/data/ef-rp/intro/samples
You can edit in browser.

**Comment by Rick-Anderson** [comment]
It's not  a scaffolding bug. For some reason we changed it. Change it back to `<h1>`
