### ISSUE TITLE
Сделал всё пошагово, но в /movies -  ошибка 404

### ISSUE THREAD

**Issue by Kezzya** [aspnet/AspNetCore.Docs.ru-ru#55]
Уже 2 раз пересоздаю проект, выполнил все указанные команды ( с миграцией и апдейтом), но  /movies раздела не существует. 

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Добавление модели в приложение Razor Pages в ASP.NET Core](https://docs.microsoft.com/ru-ru/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs.ru-ru/blob/live/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @Kezzya
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
I’ve been rebuilding the project 2 times already, I have completed all the indicated commands (with migration and update), but the / movies section does not exist.

Recommend close. The code and instructions work.

**Comment by Kezzya** [comment]
Sry. My fault.
