### ISSUE TITLE
не правильно работает Скрытие текста

### ISSUE THREAD

**Issue by KANekT** [aspnet/AspNetCore.Docs.ru-ru#57]
Щелкните здесь, чтобы развернуть список пакетов, которые больше не создаются

скрывает весь текст

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Миграция с ASP.NET Core 2,2 на 3,0](https://docs.microsoft.com/ru-ru/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs.ru-ru/blob/live/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @KANekT
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team
