### ISSUE TITLE
Поиск по жанру

### ISSUE THREAD

**Issue by aacronix** [aspnet/AspNetCore.Docs.ru-ru#60]
При поиске по жанру, учитывается регистр.
В примере указано что при поисковой строке "ghost" найдутся 2 фильма - этого не происходит, при заглавной букве поиск будет соответствовать.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: cc54dbf8-e6fe-a212-b2cd-c015a6ba5439
* Version Independent ID: b96b0b44-3e3a-a6c2-6b2b-c7bab4b78f0d
* Content: [Добавление поиска на страницы Razor ASP.NET Core](https://docs.microsoft.com/ru-ru/aspnet/core/tutorials/razor-pages/search?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/search.md](https://github.com/aspnet/AspNetCore.Docs.ru-ru/blob/live/aspnetcore/tutorials/razor-pages/search.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @aacronix
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
When searching by genre, case sensitive.
The example shows that with the search string "ghost" there are 2 movies - this does not happen, with a capital letter, the search will match.

Per the article:
Note: The Contains method is run on the database, not in the C# code. The case sensitivity on the query depends on the database and the collation. On SQL Server, Contains maps to SQL LIKE, which is case insensitive. **In SQLite, with the default collation, it's case sensitive.**

Recommend closing.

**Comment by SunnyDeng** [comment]
When searching by genre, case sensitive.
The example shows that with the search string "ghost" there are 2 movies - this does not happen, with a capital letter, the search will match.
Per the article:
Note: The Contains method is run on the database, not in the C# code. The case sensitivity on the query depends on the database and the collation. On SQL Server, Contains maps to SQL LIKE, which is case insensitive. In SQLite, with the default collation, it's case sensitive.
Recommend closing.
#please-translate

**Comment by Rick-Anderson** [comment]
По статье:
Примечание. Метод Contains запускается в базе данных, а не в коде C #. Чувствительность к регистру в запросе зависит от базы данных и параметров сортировки. На SQL Server Содержит сопоставления с SQL LIKE, которые не чувствительны к регистру. В SQLite, с сопоставлением по умолчанию, он чувствителен к регистру.
Рекомендую закрыть.

**Comment by SunnyDeng** [comment]
Hi @aacronix close this issue as the content owner explained and recommend.
