### ISSUE TITLE
Проблемы перевода параграфа "Настройка проверки сертификата"

### ISSUE THREAD

**Issue by TdMxm** [aspnet/AspNetCore.Docs.ru-ru#63]
Алловедцертификатетипес = цепочка, Селфсигнед или все (цепочка | Селфсигнед)
валидатецертификатеусе
Думаю тут должны быть оригинальные английские названия 

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 35b7960d-6de5-78ee-bc45-d7218239bbc8
* Version Independent ID: d2db534b-198a-dc99-5b5a-0525582d39ac
* Content: [Настройка проверки подлинности сертификата в ASP.NET Core](https://docs.microsoft.com/ru-ru/aspnet/core/security/authentication/certauth?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/security/authentication/certauth.md](https://github.com/aspnet/AspNetCore.Docs.ru-ru/blob/live/aspnetcore/security/authentication/certauth.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @blowdart
* Microsoft Alias: **bdorrans**

**Comment by srvbpigh** [comment]
Hello, @TdMxm
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by TdMxm** [comment]
This issue is very simular to #64, so i think it can be closed as well

**Comment by CeciAc** [comment]
Здравствуйте, @TdMxm 
Спасибо за отзыв. 
Наши лингвисты рассмотрели Ваши предложения и приняли их. Мы внедрили Ваши правки в обновленные статьи на сайте документации, опубликованные на следующих страницах: https://docs.microsoft.com/ru-ru/aspnet/core/security/authentication/certauth?view=aspnetcore-3.0#feedback
Мы очень ценим Ваш вклад в наши статьи и будем рады получить другие полезные отзывы. 
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
