### ISSUE TITLE
Incorrect translations and undesired transliterations

### ISSUE THREAD

**Issue by TdMxm** [aspnet/AspNetCore.Docs.ru-ru#64]
> HTTP-соединения пула с Хттпклиентфактори
> Хттпклиентфактори был представлен в ASP.NET Core 2,1 в качестве решения этой проблемы. 
> Используйте хттпклиентфактори для получения экземпляров HttpClient. Дополнительные сведения см. в статье Использование хттпклиентфактори для реализации устойчивых HTTP-запросов.

HttpClientFactory(Хттпклиентфактори) should not be transliterated

> Предпочитать Реадформасинк по запросу. Form

"Предпочитайте использовать ReadFromAsync вместо Request.Form" is better
>HttpContext.Request.Form может быть безопасно прочитан только со следующими условиями

"HttpContext.Request.Form может быть безопасно прочитан только при соблюдении следующих условий" is better

>Не Выменяйте это: В следующем примере используется HttpContext.Request.Form. HttpContext.Request.Form использует [sync через Async @ no__t-2 и может привести к нехватке пула потоков.

"**Не делайте так**. Следующий пример использует HttpContext.Request.Form. HttpContext.Request.Form выполняет [синхронное ожидание результата асинхронного метода](https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#warning-sync-over-async) что может привести к исчерпанию пула потоков." is better

> Не хранить Ихттпконтекстакцессор. HttpContext в поле
> Ихттпконтекстакцессор. HttpContext возвращает HttpContext

IHttpContextAccessor(Ихттпконтекстакцессор) should not be transliterated

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 9599d917-4e43-f1ae-452a-1f11aaa985ed
* Version Independent ID: 5cc05b6c-c671-3607-3217-7db73ebc1f28
* Content: [Рекомендации по повышению производительности ASP.NET Core](https://docs.microsoft.com/ru-ru/aspnet/core/performance/performance-best-practices?view=aspnetcore-3.0)
* Content Source: [aspnetcore/performance/performance-best-practices.md](https://github.com/aspnet/AspNetCore.Docs.ru-ru/blob/live/aspnetcore/performance/performance-best-practices.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @TdMxm
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @TdMxm 

Thank you for your feedback. The page in question has been machine-translated, which is not always perfectly understandable. We recently added a "Read in English" option on the right which allows you to switch to the English version without having to change the language settings.

Microsoft DOCS International Team
Kind regards,
