### ISSUE TITLE
Нарушение принципов MVC

### ISSUE THREAD

**Issue by aford9880** [aspnet/AspNetCore.Docs.ru-ru#65]
Выражение "var movieGenreVM = new MovieGenreViewModel" в контроллере не нарушает принципы MVC, создавая жесткую привязку метода действия контроллера к модели? Поправьте. пожалуйста, если я не прав. Спасибо)

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: f9b9859c-b83c-5fc3-41d5-15531232185f
* Version Independent ID: 5438de31-8562-3747-d1a5-2a4622252fc1
* Content: [Добавление поиска в приложение MVC ASP.NET Core](https://docs.microsoft.com/ru-ru/aspnet/core/tutorials/first-mvc-app/search?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/search.md](https://github.com/aspnet/AspNetCore.Docs.ru-ru/blob/live/aspnetcore/tutorials/first-mvc-app/search.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @aford9880
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [aspnet/AspNetCore.Docs #16014](https://github.com/aspnet/AspNetCore.Docs/issues/16014) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Здравствуйте, @aford9880 
Благодарим Вас за участие. Ваш отзыв связан с исходной документацией. 
Поэтому мы переносим Вашу заявку в репозиторий по английскому языку. Ее состояние можно просмотреть здесь: https://github.com/aspnet/AspNetCore.Docs/issues/16014
Мы очень ценим Ваш вклад в наши статьи.  
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
