### ISSUE TITLE
Issue with other DBs like MySql

### ISSUE THREAD

**Issue by flydyman** [aspnet/AspNetCore.Docs.ru-ru#66]
While doing this tutorial, I run into issue with comparing searchString because ghost!=Ghost. There is smallfix at Index method:
```s
public async Task&lt;IActionResult&gt; Index(string searchString)
        {
            var movies = from m in _context.Movie select m;
            if(!String.IsNullOrEmpty(searchString))
            {
                searchString = searchString.ToLower();
                movies = movies.Where(s=&gt;s.Title.ToLower().Contains(searchString));
            }
            return View(await movies.ToListAsync());
        }
```
---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: f9b9859c-b83c-5fc3-41d5-15531232185f
* Version Independent ID: 5438de31-8562-3747-d1a5-2a4622252fc1
* Content: [Добавление поиска в приложение MVC ASP.NET Core](https://docs.microsoft.com/ru-ru/aspnet/core/tutorials/first-mvc-app/search?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/search.md](https://github.com/aspnet/AspNetCore.Docs.ru-ru/blob/live/aspnetcore/tutorials/first-mvc-app/search.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @flydyman
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
Please close. This is discussed in the tutorial.

**Comment by flydyman** [comment]
As you wish
