### ISSUE TITLE
Ужасный русский текст

### ISSUE THREAD

**Issue by stilettk** [aspnet/AspNetCore.Docs.ru-ru#68]
Пример: кнгкбкаусентикатеденкрипторконфигуратион 

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: b63ab082-ad30-b00d-ecd1-ca88eee1659e
* Version Independent ID: 69818122-e47a-3fed-ea37-8009f66e2a5c
* Content: [Настройка защиты данных ASP.NET Core](https://docs.microsoft.com/ru-ru/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/data-protection/configuration/overview.md](https://github.com/aspnet/AspNetCore.Docs.ru-ru/blob/live/aspnetcore/security/data-protection/configuration/overview.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @stilettk
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Здравствуйте, @stilettk 
Спасибо за отзыв. Рассматриваемая страница переведена с использованием машинного перевода, который не всегда идеально понятен. Недавно мы добавили справа на странице функцию «Прочитать на английском», которая позволяет переключиться на английскую версию, не меняя настройки языка. 
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт

**Comment by stilettk** [comment]
@CeciAc Я помню, что была такая функция, как "прочитать на английском", но сейчас ее нет:
![image](https://user-images.githubusercontent.com/7068016/71040022-aba6b000-2136-11ea-8856-a57249d8d9f9.png)
